### ISSUE TITLE
Docker on a public port different from 80 login failure

### ISSUE THREAD

**Issue by ccolonna** [rhizomik/rhizomerEye#60]
Good morning,

I'm trying to setup an instance of dockerized ```rhyzomerEye``` behind a reverse proxy. The reverse proxy runs on default port for http 80.

I tried to modify ```docker-compose.yml``` assigning port 8081 as public one. Frontend app works but i can't succesfully login.

Trying to login with:
- username: admin or user
- password: password

I received this error from the API.

```Http failure response for http://localhost:8080/user: 504 Gateway Timeout```

Broswer tab doesn't seem to show any network interaction.

Everything works ok launching ```rhyzomerEye``` on port 80.

**Comment by rogargon** [comment]
Hello @ccolonna,

Please, note that if you change the port where the frontend is deployed, you should add it to the ALLOWED_ORIGINS for the backend. For instance, using a docker-compose to deploy both front and backend:

```
version: '3'
services:
  rhizomer-api:
    image: rhizomik/rhizomer-api
    container_name: rhizomer-api
    ports:
      - "8080:8080"
    environment:
      - ALLOWED_ORIGINS=http://localhost:8081
      - RHIZOMER_DEFAULT_PASSWORD=password
  rhizomer:
    image: rhizomik/rhizomer-eye
    container_name: rhizomer
    ports:
      - "8081:80"
    environment:
      - API_URL=http://localhost:8080
```

Moreover, if you are running them behind a proxy, take into account that both frontend and backend need to be proxied. The user will access from her/his machine the frontend but also, through the client, the backend.
